"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class MockPayload(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Status:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _StatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[MockPayload._Status.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: MockPayload._Status.ValueType  # 0
        OK: MockPayload._Status.ValueType  # 1
        FAILED: MockPayload._Status.ValueType  # 2

    class Status(_Status, metaclass=_StatusEnumTypeWrapper):
        """enum"""

    UNKNOWN: MockPayload.Status.ValueType  # 0
    OK: MockPayload.Status.ValueType  # 1
    FAILED: MockPayload.Status.ValueType  # 2

    @typing.final
    class Metadata(google.protobuf.message.Message):
        """중첩 메시지"""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    WIDTH_FIELD_NUMBER: builtins.int
    HEIGHT_FIELD_NUMBER: builtins.int
    CONFIDENCE_FIELD_NUMBER: builtins.int
    TEMPERATURE_FIELD_NUMBER: builtins.int
    IS_VALID_FIELD_NUMBER: builtins.int
    LABEL_FIELD_NUMBER: builtins.int
    IMAGE_DATA_FIELD_NUMBER: builtins.int
    POINTS_FIELD_NUMBER: builtins.int
    TAGS_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    width: builtins.int
    """정수형"""
    height: builtins.int
    confidence: builtins.float
    """부동소수점"""
    temperature: builtins.float
    is_valid: builtins.bool
    """불리언"""
    label: builtins.str
    """문자열"""
    image_data: builtins.bytes
    """바이트 배열"""
    status: global___MockPayload.Status.ValueType
    @property
    def points(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """반복 (리스트)"""

    @property
    def tags(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___MockPayload.Metadata]: ...
    def __init__(
        self,
        *,
        width: builtins.int = ...,
        height: builtins.int = ...,
        confidence: builtins.float = ...,
        temperature: builtins.float = ...,
        is_valid: builtins.bool = ...,
        label: builtins.str = ...,
        image_data: builtins.bytes = ...,
        points: collections.abc.Iterable[builtins.int] | None = ...,
        tags: collections.abc.Iterable[global___MockPayload.Metadata] | None = ...,
        status: global___MockPayload.Status.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["confidence", b"confidence", "height", b"height", "image_data", b"image_data", "is_valid", b"is_valid", "label", b"label", "points", b"points", "status", b"status", "tags", b"tags", "temperature", b"temperature", "width", b"width"]) -> None: ...

global___MockPayload = MockPayload
